// Generated by fuzzing/gen_targets.py from `tac --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "before", short: Some('b'), kind: Flag },
    OptSpec { long: "regex", short: Some('r'), kind: Flag },
    OptSpec { long: "separator", short: Some('s'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("tac", OPTS, uu_tac::uumain, &case);
});
