// Generated by fuzzing/gen_targets.py from `realpath --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "quiet", short: Some('q'), kind: Flag },
    OptSpec { long: "strip", short: Some('s'), kind: Flag },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
    OptSpec { long: "logical", short: Some('L'), kind: Flag },
    OptSpec { long: "physical", short: Some('P'), kind: Flag },
    OptSpec { long: "canonicalize", short: Some('E'), kind: Flag },
    OptSpec { long: "canonicalize-existing", short: Some('e'), kind: Flag },
    OptSpec { long: "canonicalize-missing", short: Some('m'), kind: Flag },
    OptSpec { long: "relative-to", short: None, kind: Value },
    OptSpec { long: "relative-base", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("realpath", OPTS, uu_realpath::uumain, &case);
});
