// Generated by fuzzing/gen_targets.py from `truncate --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "io-blocks", short: Some('o'), kind: Flag },
    OptSpec { long: "no-create", short: Some('c'), kind: Flag },
    OptSpec { long: "reference", short: Some('r'), kind: Value },
    OptSpec { long: "size", short: Some('s'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("truncate", OPTS, uu_truncate::uumain, &case);
});
