// Generated by fuzzing/gen_targets.py from `echo --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('n'), kind: Flag },
    OptSpec { long: "", short: Some('e'), kind: Flag },
    OptSpec { long: "", short: Some('E'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("echo", OPTS, uu_echo::uumain, &case);
});
