// Generated by fuzzing/gen_targets.py from `basename --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "multiple", short: Some('a'), kind: Flag },
    OptSpec { long: "suffix", short: Some('s'), kind: Value },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("basename", OPTS, uu_basename::uumain, &case);
});
