// Generated by fuzzing/gen_targets.py from `rm --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "force", short: Some('f'), kind: Flag },
    OptSpec { long: "", short: Some('i'), kind: Flag },
    OptSpec { long: "", short: Some('I'), kind: Flag },
    OptSpec { long: "one-file-system", short: None, kind: Flag },
    OptSpec { long: "no-preserve-root", short: None, kind: Flag },
    OptSpec { long: "preserve-root", short: None, kind: Flag },
    OptSpec { long: "recursive", short: Some('r'), kind: Flag },
    OptSpec { long: "dir", short: Some('d'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "progress", short: Some('g'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("rm", OPTS, uu_rm::uumain, &case);
});
