// Generated by fuzzing/gen_targets.py from `timeout --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "foreground", short: Some('f'), kind: Flag },
    OptSpec { long: "kill-after", short: Some('k'), kind: Value },
    OptSpec { long: "preserve-status", short: Some('p'), kind: Flag },
    OptSpec { long: "signal", short: Some('s'), kind: Value },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("timeout", OPTS, uu_timeout::uumain, &case);
});
