// Generated by fuzzing/gen_targets.py from `nproc --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: None, kind: Flag },
    OptSpec { long: "ignore", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("nproc", OPTS, uu_nproc::uumain, &case);
});
