// Generated by fuzzing/gen_targets.py from `uptime --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "since", short: Some('s'), kind: Flag },
    OptSpec { long: "pretty", short: Some('p'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("uptime", OPTS, uu_uptime::uumain, &case);
});
