// Generated by fuzzing/gen_targets.py from `pwd --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "logical", short: Some('L'), kind: Flag },
    OptSpec { long: "physical", short: Some('P'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("pwd", OPTS, uu_pwd::uumain, &case);
});
