// Generated by fuzzing/gen_targets.py from `fold --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "bytes", short: Some('b'), kind: Flag },
    OptSpec { long: "characters", short: Some('c'), kind: Flag },
    OptSpec { long: "spaces", short: Some('s'), kind: Flag },
    OptSpec { long: "width", short: Some('w'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("fold", OPTS, uu_fold::uumain, &case);
});
