// Generated by fuzzing/gen_targets.py from `id --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "ignore", short: Some('a'), kind: Flag },
    OptSpec { long: "", short: Some('A'), kind: Flag },
    OptSpec { long: "user", short: Some('u'), kind: Flag },
    OptSpec { long: "group", short: Some('g'), kind: Flag },
    OptSpec { long: "groups", short: Some('G'), kind: Flag },
    OptSpec { long: "", short: Some('p'), kind: Flag },
    OptSpec { long: "name", short: Some('n'), kind: Flag },
    OptSpec { long: "", short: Some('P'), kind: Flag },
    OptSpec { long: "real", short: Some('r'), kind: Flag },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
    OptSpec { long: "context", short: Some('Z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("id", OPTS, uu_id::uumain, &case);
});
