// Generated by fuzzing/gen_targets.py from `uname --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "kernel-name", short: Some('s'), kind: Flag },
    OptSpec { long: "nodename", short: Some('n'), kind: Flag },
    OptSpec { long: "kernel-release", short: Some('r'), kind: Flag },
    OptSpec { long: "kernel-version", short: Some('v'), kind: Flag },
    OptSpec { long: "machine", short: Some('m'), kind: Flag },
    OptSpec { long: "operating-system", short: Some('o'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("uname", OPTS, uu_uname::uumain, &case);
});
