// Generated by fuzzing/gen_targets.py from `tail --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "bytes", short: Some('c'), kind: Value },
    OptSpec { long: "lines", short: Some('n'), kind: Value },
    OptSpec { long: "pid", short: None, kind: Value },
    OptSpec { long: "quiet", short: Some('q'), kind: Flag },
    OptSpec { long: "sleep-interval", short: Some('s'), kind: Value },
    OptSpec { long: "max-unchanged-stats", short: None, kind: Value },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
    OptSpec { long: "use-polling", short: None, kind: Flag },
    OptSpec { long: "retry", short: None, kind: Flag },
    OptSpec { long: "", short: Some('F'), kind: Flag },
    OptSpec { long: "debug", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("tail", OPTS, uu_tail::uumain, &case);
});
