// Generated by fuzzing/gen_targets.py from `cp --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "target-directory", short: Some('t'), kind: Value },
    OptSpec { long: "no-target-directory", short: Some('T'), kind: Flag },
    OptSpec { long: "interactive", short: Some('i'), kind: Flag },
    OptSpec { long: "link", short: Some('l'), kind: Flag },
    OptSpec { long: "no-clobber", short: Some('n'), kind: Flag },
    OptSpec { long: "recursive", short: Some('R'), kind: Flag },
    OptSpec { long: "strip-trailing-slashes", short: None, kind: Flag },
    OptSpec { long: "debug", short: None, kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "symbolic-link", short: Some('s'), kind: Flag },
    OptSpec { long: "force", short: Some('f'), kind: Flag },
    OptSpec { long: "remove-destination", short: None, kind: Flag },
    OptSpec { long: "", short: Some('b'), kind: Flag },
    OptSpec { long: "suffix", short: Some('S'), kind: Value },
    OptSpec { long: "", short: Some('u'), kind: Flag },
    OptSpec { long: "attributes-only", short: None, kind: Flag },
    OptSpec { long: "preserve-default-attributes", short: Some('p'), kind: Flag },
    OptSpec { long: "parents", short: None, kind: Flag },
    OptSpec { long: "no-dereference", short: Some('P'), kind: Flag },
    OptSpec { long: "dereference", short: Some('L'), kind: Flag },
    OptSpec { long: "", short: Some('H'), kind: Flag },
    OptSpec { long: "archive", short: Some('a'), kind: Flag },
    OptSpec { long: "", short: Some('d'), kind: Flag },
    OptSpec { long: "one-file-system", short: Some('x'), kind: Flag },
    OptSpec { long: "sparse", short: None, kind: Value },
    OptSpec { long: "", short: Some('Z'), kind: Flag },
    OptSpec { long: "progress", short: Some('g'), kind: Flag },
    OptSpec { long: "copy-contents", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("cp", OPTS, uu_cp::uumain, &case);
});
