// Generated by fuzzing/gen_targets.py from `vdir --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('C'), kind: Flag },
    OptSpec { long: "long", short: Some('l'), kind: Flag },
    OptSpec { long: "", short: Some('x'), kind: Flag },
    OptSpec { long: "tabsize", short: Some('T'), kind: Value },
    OptSpec { long: "", short: Some('m'), kind: Flag },
    OptSpec { long: "zero", short: None, kind: Flag },
    OptSpec { long: "dired", short: Some('D'), kind: Flag },
    OptSpec { long: "", short: Some('1'), kind: Flag },
    OptSpec { long: "", short: Some('o'), kind: Flag },
    OptSpec { long: "", short: Some('g'), kind: Flag },
    OptSpec { long: "numeric-uid-gid", short: Some('n'), kind: Flag },
    OptSpec { long: "quoting-style", short: None, kind: Value },
    OptSpec { long: "literal", short: Some('N'), kind: Flag },
    OptSpec { long: "escape", short: Some('b'), kind: Flag },
    OptSpec { long: "quote-name", short: Some('Q'), kind: Flag },
    OptSpec { long: "hide-control-chars", short: Some('q'), kind: Flag },
    OptSpec { long: "show-control-chars", short: None, kind: Flag },
    OptSpec { long: "", short: Some('c'), kind: Flag },
    OptSpec { long: "", short: Some('u'), kind: Flag },
    OptSpec { long: "hide", short: None, kind: Value },
    OptSpec { long: "ignore", short: Some('I'), kind: Value },
    OptSpec { long: "ignore-backups", short: Some('B'), kind: Flag },
    OptSpec { long: "", short: Some('S'), kind: Flag },
    OptSpec { long: "", short: Some('t'), kind: Flag },
    OptSpec { long: "", short: Some('v'), kind: Flag },
    OptSpec { long: "", short: Some('X'), kind: Flag },
    OptSpec { long: "", short: Some('U'), kind: Flag },
    OptSpec { long: "dereference", short: Some('L'), kind: Flag },
    OptSpec { long: "dereference-command-line-symlink-to-dir", short: None, kind: Flag },
    OptSpec { long: "dereference-command-line", short: Some('H'), kind: Flag },
    OptSpec { long: "no-group", short: Some('G'), kind: Flag },
    OptSpec { long: "author", short: None, kind: Flag },
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "almost-all", short: Some('A'), kind: Flag },
    OptSpec { long: "", short: Some('f'), kind: Flag },
    OptSpec { long: "directory", short: Some('d'), kind: Flag },
    OptSpec { long: "human-readable", short: Some('h'), kind: Flag },
    OptSpec { long: "kibibytes", short: Some('k'), kind: Flag },
    OptSpec { long: "si", short: None, kind: Flag },
    OptSpec { long: "inode", short: Some('i'), kind: Flag },
    OptSpec { long: "reverse", short: Some('r'), kind: Flag },
    OptSpec { long: "recursive", short: Some('R'), kind: Flag },
    OptSpec { long: "width", short: Some('w'), kind: Value },
    OptSpec { long: "size", short: Some('s'), kind: Flag },
    OptSpec { long: "indicator-style", short: None, kind: Value },
    OptSpec { long: "file-type", short: None, kind: Flag },
    OptSpec { long: "", short: Some('p'), kind: Flag },
    OptSpec { long: "time-style", short: None, kind: Value },
    OptSpec { long: "full-time", short: None, kind: Flag },
    OptSpec { long: "context", short: Some('Z'), kind: Flag },
    OptSpec { long: "group-directories-first", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("vdir", OPTS, uu_vdir::uumain, &case);
});
