// Generated by fuzzing/gen_targets.py from `dircolors --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "sh", short: Some('b'), kind: Flag },
    OptSpec { long: "csh", short: Some('c'), kind: Flag },
    OptSpec { long: "print-database", short: Some('p'), kind: Flag },
    OptSpec { long: "print-ls-colors", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("dircolors", OPTS, uu_dircolors::uumain, &case);
});
