// Generated by fuzzing/gen_targets.py from `ptx --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "auto-reference", short: Some('A'), kind: Flag },
    OptSpec { long: "traditional", short: Some('G'), kind: Flag },
    OptSpec { long: "flag-truncation", short: Some('F'), kind: Value },
    OptSpec { long: "macro-name", short: Some('M'), kind: Value },
    OptSpec { long: "", short: Some('O'), kind: Flag },
    OptSpec { long: "", short: Some('T'), kind: Flag },
    OptSpec { long: "right-side-refs", short: Some('R'), kind: Flag },
    OptSpec { long: "sentence-regexp", short: Some('S'), kind: Value },
    OptSpec { long: "word-regexp", short: Some('W'), kind: Value },
    OptSpec { long: "break-file", short: Some('b'), kind: Value },
    OptSpec { long: "ignore-case", short: Some('f'), kind: Flag },
    OptSpec { long: "gap-size", short: Some('g'), kind: Value },
    OptSpec { long: "ignore-file", short: Some('i'), kind: Value },
    OptSpec { long: "only-file", short: Some('o'), kind: Value },
    OptSpec { long: "references", short: Some('r'), kind: Flag },
    OptSpec { long: "typeset-mode", short: Some('t'), kind: Flag },
    OptSpec { long: "width", short: Some('w'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("ptx", OPTS, uu_ptx::uumain, &case);
});
