// Generated by fuzzing/gen_targets.py from `stty --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "save", short: Some('g'), kind: Flag },
    OptSpec { long: "file", short: Some('F'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("stty", OPTS, uu_stty::uumain, &case);
});
