// Generated by fuzzing/gen_targets.py from `shuf --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "echo", short: Some('e'), kind: Flag },
    OptSpec { long: "input-range", short: Some('i'), kind: Value },
    OptSpec { long: "head-count", short: Some('n'), kind: Value },
    OptSpec { long: "output", short: Some('o'), kind: Value },
    OptSpec { long: "random-seed", short: None, kind: Value },
    OptSpec { long: "random-source", short: None, kind: Value },
    OptSpec { long: "repeat", short: Some('r'), kind: Flag },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("shuf", OPTS, uu_shuf::uumain, &case);
});
