// Generated by fuzzing/gen_targets.py from `pinky --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('l'), kind: Flag },
    OptSpec { long: "", short: Some('b'), kind: Flag },
    OptSpec { long: "", short: Some('h'), kind: Flag },
    OptSpec { long: "", short: Some('p'), kind: Flag },
    OptSpec { long: "", short: Some('s'), kind: Flag },
    OptSpec { long: "", short: Some('f'), kind: Flag },
    OptSpec { long: "", short: Some('w'), kind: Flag },
    OptSpec { long: "", short: Some('i'), kind: Flag },
    OptSpec { long: "", short: Some('q'), kind: Flag },
    OptSpec { long: "lookup", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("pinky", OPTS, uu_pinky::uumain, &case);
});
