// Generated by fuzzing/gen_targets.py from `factor --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "exponents", short: Some('h'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("factor", OPTS, uu_factor::uumain, &case);
});
