// Generated by fuzzing/gen_targets.py from `sum --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('r'), kind: Flag },
    OptSpec { long: "sysv", short: Some('s'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("sum", OPTS, uu_sum::uumain, &case);
});
