// Generated by fuzzing/gen_targets.py from `pathchk --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('p'), kind: Flag },
    OptSpec { long: "", short: Some('P'), kind: Flag },
    OptSpec { long: "portability", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("pathchk", OPTS, uu_pathchk::uumain, &case);
});
