// Generated by fuzzing/gen_targets.py from `base64 --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "decode", short: Some('d'), kind: Flag },
    OptSpec { long: "ignore-garbage", short: Some('i'), kind: Flag },
    OptSpec { long: "wrap", short: Some('w'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("base64", OPTS, uu_base64::uumain, &case);
});
