// Generated by fuzzing/gen_targets.py from `hostname --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "domain", short: Some('d'), kind: Flag },
    OptSpec { long: "ip-address", short: Some('i'), kind: Flag },
    OptSpec { long: "fqdn", short: Some('f'), kind: Flag },
    OptSpec { long: "short", short: Some('s'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("hostname", OPTS, uu_hostname::uumain, &case);
});
