// Generated by fuzzing/gen_targets.py from `du --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "apparent-size", short: Some('A'), kind: Flag },
    OptSpec { long: "block-size", short: Some('B'), kind: Value },
    OptSpec { long: "bytes", short: Some('b'), kind: Flag },
    OptSpec { long: "total", short: Some('c'), kind: Flag },
    OptSpec { long: "max-depth", short: Some('d'), kind: Value },
    OptSpec { long: "human-readable", short: Some('h'), kind: Flag },
    OptSpec { long: "inodes", short: None, kind: Flag },
    OptSpec { long: "", short: Some('k'), kind: Flag },
    OptSpec { long: "count-links", short: Some('l'), kind: Flag },
    OptSpec { long: "dereference", short: Some('L'), kind: Flag },
    OptSpec { long: "dereference-args", short: Some('D'), kind: Flag },
    OptSpec { long: "no-dereference", short: Some('P'), kind: Flag },
    OptSpec { long: "", short: Some('m'), kind: Flag },
    OptSpec { long: "null", short: Some('0'), kind: Flag },
    OptSpec { long: "separate-dirs", short: Some('S'), kind: Flag },
    OptSpec { long: "summarize", short: Some('s'), kind: Flag },
    OptSpec { long: "si", short: None, kind: Flag },
    OptSpec { long: "one-file-system", short: Some('x'), kind: Flag },
    OptSpec { long: "threshold", short: Some('t'), kind: Value },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "exclude", short: None, kind: Value },
    OptSpec { long: "exclude-from", short: Some('X'), kind: Value },
    OptSpec { long: "files0-from", short: None, kind: Value },
    OptSpec { long: "time-style", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("du", OPTS, uu_du::uumain, &case);
});
