// Generated by fuzzing/gen_targets.py from `sha224sum --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "check", short: Some('c'), kind: Flag },
    OptSpec { long: "warn", short: Some('w'), kind: Flag },
    OptSpec { long: "status", short: None, kind: Flag },
    OptSpec { long: "quiet", short: None, kind: Flag },
    OptSpec { long: "ignore-missing", short: None, kind: Flag },
    OptSpec { long: "strict", short: None, kind: Flag },
    OptSpec { long: "tag", short: None, kind: Flag },
    OptSpec { long: "text", short: Some('t'), kind: Flag },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("sha224sum", OPTS, uu_sha224sum::uumain, &case);
});
