// Generated by fuzzing/gen_targets.py from `printenv --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "null", short: Some('0'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("printenv", OPTS, uu_printenv::uumain, &case);
});
