// Generated by fuzzing/gen_targets.py from `basenc --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "decode", short: Some('d'), kind: Flag },
    OptSpec { long: "ignore-garbage", short: Some('i'), kind: Flag },
    OptSpec { long: "wrap", short: Some('w'), kind: Value },
    OptSpec { long: "base64", short: None, kind: Flag },
    OptSpec { long: "base64url", short: None, kind: Flag },
    OptSpec { long: "base32", short: None, kind: Flag },
    OptSpec { long: "base32hex", short: None, kind: Flag },
    OptSpec { long: "base16", short: None, kind: Flag },
    OptSpec { long: "base2lsbf", short: None, kind: Flag },
    OptSpec { long: "base2msbf", short: None, kind: Flag },
    OptSpec { long: "z85", short: None, kind: Flag },
    OptSpec { long: "base58", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("basenc", OPTS, uu_basenc::uumain, &case);
});
