// Generated by fuzzing/gen_targets.py from `fmt --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "crown-margin", short: Some('c'), kind: Flag },
    OptSpec { long: "tagged-paragraph", short: Some('t'), kind: Flag },
    OptSpec { long: "preserve-headers", short: Some('m'), kind: Flag },
    OptSpec { long: "split-only", short: Some('s'), kind: Flag },
    OptSpec { long: "uniform-spacing", short: Some('u'), kind: Flag },
    OptSpec { long: "prefix", short: Some('p'), kind: Value },
    OptSpec { long: "skip-prefix", short: Some('P'), kind: Value },
    OptSpec { long: "exact-prefix", short: Some('x'), kind: Flag },
    OptSpec { long: "exact-skip-prefix", short: Some('X'), kind: Flag },
    OptSpec { long: "width", short: Some('w'), kind: Value },
    OptSpec { long: "goal", short: Some('g'), kind: Value },
    OptSpec { long: "quick", short: Some('q'), kind: Flag },
    OptSpec { long: "tab-width", short: Some('T'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("fmt", OPTS, uu_fmt::uumain, &case);
});
