// Generated by fuzzing/gen_targets.py from `mv --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "force", short: Some('f'), kind: Flag },
    OptSpec { long: "interactive", short: Some('i'), kind: Flag },
    OptSpec { long: "no-clobber", short: Some('n'), kind: Flag },
    OptSpec { long: "strip-trailing-slashes", short: None, kind: Flag },
    OptSpec { long: "", short: Some('b'), kind: Flag },
    OptSpec { long: "suffix", short: Some('S'), kind: Value },
    OptSpec { long: "", short: Some('u'), kind: Flag },
    OptSpec { long: "target-directory", short: Some('t'), kind: Value },
    OptSpec { long: "no-target-directory", short: Some('T'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "progress", short: Some('g'), kind: Flag },
    OptSpec { long: "", short: Some('Z'), kind: Flag },
    OptSpec { long: "debug", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("mv", OPTS, uu_mv::uumain, &case);
});
