// Generated by fuzzing/gen_targets.py from `expand --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "initial", short: Some('i'), kind: Flag },
    OptSpec { long: "tabs", short: Some('t'), kind: Value },
    OptSpec { long: "no-utf8", short: Some('U'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("expand", OPTS, uu_expand::uumain, &case);
});
