// Generated by fuzzing/gen_targets.py from `tty --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "silent", short: Some('s'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("tty", OPTS, uu_tty::uumain, &case);
});
