// Generated by fuzzing/gen_targets.py from `mktemp --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "directory", short: Some('d'), kind: Flag },
    OptSpec { long: "dry-run", short: Some('u'), kind: Flag },
    OptSpec { long: "quiet", short: Some('q'), kind: Flag },
    OptSpec { long: "suffix", short: None, kind: Value },
    OptSpec { long: "", short: Some('p'), kind: Value },
    OptSpec { long: "", short: Some('t'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("mktemp", OPTS, uu_mktemp::uumain, &case);
});
