// Generated by fuzzing/gen_targets.py from `who --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "boot", short: Some('b'), kind: Flag },
    OptSpec { long: "dead", short: Some('d'), kind: Flag },
    OptSpec { long: "heading", short: Some('H'), kind: Flag },
    OptSpec { long: "login", short: Some('l'), kind: Flag },
    OptSpec { long: "lookup", short: None, kind: Flag },
    OptSpec { long: "", short: Some('m'), kind: Flag },
    OptSpec { long: "process", short: Some('p'), kind: Flag },
    OptSpec { long: "count", short: Some('q'), kind: Flag },
    OptSpec { long: "runlevel", short: Some('r'), kind: Flag },
    OptSpec { long: "short", short: Some('s'), kind: Flag },
    OptSpec { long: "time", short: Some('t'), kind: Flag },
    OptSpec { long: "users", short: Some('u'), kind: Flag },
    OptSpec { long: "mesg", short: Some('T'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("who", OPTS, uu_who::uumain, &case);
});
