// Generated by fuzzing/gen_targets.py from `mkdir --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "mode", short: Some('m'), kind: Value },
    OptSpec { long: "parents", short: Some('p'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "", short: Some('Z'), kind: Flag },
    OptSpec { long: "context", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("mkdir", OPTS, uu_mkdir::uumain, &case);
});
