// Generated by fuzzing/gen_targets.py from `shred --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "force", short: Some('f'), kind: Flag },
    OptSpec { long: "iterations", short: Some('n'), kind: Value },
    OptSpec { long: "size", short: Some('s'), kind: Value },
    OptSpec { long: "", short: Some('u'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "exact", short: Some('x'), kind: Flag },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
    OptSpec { long: "random-source", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("shred", OPTS, uu_shred::uumain, &case);
});
