// Generated by fuzzing/gen_targets.py from `join --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('a'), kind: Value },
    OptSpec { long: "", short: Some('v'), kind: Value },
    OptSpec { long: "", short: Some('e'), kind: Value },
    OptSpec { long: "ignore-case", short: Some('i'), kind: Flag },
    OptSpec { long: "", short: Some('j'), kind: Value },
    OptSpec { long: "", short: Some('o'), kind: Value },
    OptSpec { long: "", short: Some('t'), kind: Value },
    OptSpec { long: "", short: Some('1'), kind: Value },
    OptSpec { long: "", short: Some('2'), kind: Value },
    OptSpec { long: "check-order", short: None, kind: Flag },
    OptSpec { long: "nocheck-order", short: None, kind: Flag },
    OptSpec { long: "header", short: None, kind: Flag },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("join", OPTS, uu_join::uumain, &case);
});
