// Generated by fuzzing/gen_targets.py from `tr --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "complement", short: Some('c'), kind: Flag },
    OptSpec { long: "delete", short: Some('d'), kind: Flag },
    OptSpec { long: "squeeze-repeats", short: Some('s'), kind: Flag },
    OptSpec { long: "truncate-set1", short: Some('t'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("tr", OPTS, uu_tr::uumain, &case);
});
