// Generated by fuzzing/gen_targets.py from `comm --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('1'), kind: Flag },
    OptSpec { long: "", short: Some('2'), kind: Flag },
    OptSpec { long: "", short: Some('3'), kind: Flag },
    OptSpec { long: "output-delimiter", short: None, kind: Value },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
    OptSpec { long: "total", short: None, kind: Flag },
    OptSpec { long: "check-order", short: None, kind: Flag },
    OptSpec { long: "nocheck-order", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("comm", OPTS, uu_comm::uumain, &case);
});
