// Generated by fuzzing/gen_targets.py from `install --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('b'), kind: Flag },
    OptSpec { long: "", short: Some('c'), kind: Flag },
    OptSpec { long: "compare", short: Some('C'), kind: Flag },
    OptSpec { long: "directory", short: Some('d'), kind: Flag },
    OptSpec { long: "", short: Some('D'), kind: Flag },
    OptSpec { long: "group", short: Some('g'), kind: Value },
    OptSpec { long: "mode", short: Some('m'), kind: Value },
    OptSpec { long: "owner", short: Some('o'), kind: Value },
    OptSpec { long: "preserve-timestamps", short: Some('p'), kind: Flag },
    OptSpec { long: "strip", short: Some('s'), kind: Flag },
    OptSpec { long: "strip-program", short: None, kind: Value },
    OptSpec { long: "suffix", short: Some('S'), kind: Value },
    OptSpec { long: "target-directory", short: Some('t'), kind: Value },
    OptSpec { long: "no-target-directory", short: Some('T'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "preserve-context", short: Some('P'), kind: Flag },
    OptSpec { long: "", short: Some('Z'), kind: Flag },
    OptSpec { long: "context", short: None, kind: Optional },
    OptSpec { long: "unprivileged", short: Some('U'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("install", OPTS, uu_install::uumain, &case);
});
