// Generated by fuzzing/gen_targets.py from `date --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "date", short: Some('d'), kind: Value },
    OptSpec { long: "file", short: Some('f'), kind: Value },
    OptSpec { long: "iso-8601", short: Some('I'), kind: Optional },
    OptSpec { long: "resolution", short: None, kind: Flag },
    OptSpec { long: "rfc-email", short: Some('R'), kind: Flag },
    OptSpec { long: "rfc-3339", short: None, kind: Value },
    OptSpec { long: "debug", short: None, kind: Flag },
    OptSpec { long: "reference", short: Some('r'), kind: Value },
    OptSpec { long: "set", short: Some('s'), kind: Value },
    OptSpec { long: "universal", short: Some('u'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("date", OPTS, uu_date::uumain, &case);
});
