// Generated by fuzzing/gen_targets.py from `readlink --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "canonicalize", short: Some('f'), kind: Flag },
    OptSpec { long: "canonicalize-existing", short: Some('e'), kind: Flag },
    OptSpec { long: "canonicalize-missing", short: Some('m'), kind: Flag },
    OptSpec { long: "no-newline", short: Some('n'), kind: Flag },
    OptSpec { long: "quiet", short: Some('q'), kind: Flag },
    OptSpec { long: "silent", short: Some('s'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("readlink", OPTS, uu_readlink::uumain, &case);
});
