// Generated by fuzzing/gen_targets.py from `uniq --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "check-chars", short: Some('w'), kind: Value },
    OptSpec { long: "count", short: Some('c'), kind: Flag },
    OptSpec { long: "ignore-case", short: Some('i'), kind: Flag },
    OptSpec { long: "repeated", short: Some('d'), kind: Flag },
    OptSpec { long: "skip-chars", short: Some('s'), kind: Value },
    OptSpec { long: "skip-fields", short: Some('f'), kind: Value },
    OptSpec { long: "unique", short: Some('u'), kind: Flag },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("uniq", OPTS, uu_uniq::uumain, &case);
});
