// Generated by fuzzing/gen_targets.py from `unexpand --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "first-only", short: Some('f'), kind: Flag },
    OptSpec { long: "tabs", short: Some('t'), kind: Value },
    OptSpec { long: "no-utf8", short: Some('U'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("unexpand", OPTS, uu_unexpand::uumain, &case);
});
