// Generated by fuzzing/gen_targets.py from `more --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "silent", short: Some('d'), kind: Flag },
    OptSpec { long: "logical", short: Some('l'), kind: Flag },
    OptSpec { long: "exit-on-eof", short: Some('e'), kind: Flag },
    OptSpec { long: "no-pause", short: Some('f'), kind: Flag },
    OptSpec { long: "print-over", short: Some('p'), kind: Flag },
    OptSpec { long: "clean-print", short: Some('c'), kind: Flag },
    OptSpec { long: "squeeze", short: Some('s'), kind: Flag },
    OptSpec { long: "lines", short: Some('n'), kind: Value },
    OptSpec { long: "number", short: None, kind: Value },
    OptSpec { long: "from-line", short: Some('F'), kind: Value },
    OptSpec { long: "pattern", short: Some('P'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("more", OPTS, uu_more::uumain, &case);
});
