// Generated by fuzzing/gen_targets.py from `mknod --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "mode", short: Some('m'), kind: Value },
    OptSpec { long: "", short: Some('Z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("mknod", OPTS, uu_mknod::uumain, &case);
});
