// Generated by fuzzing/gen_targets.py from `cat --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "show-all", short: Some('A'), kind: Flag },
    OptSpec { long: "number-nonblank", short: Some('b'), kind: Flag },
    OptSpec { long: "", short: Some('e'), kind: Flag },
    OptSpec { long: "show-ends", short: Some('E'), kind: Flag },
    OptSpec { long: "number", short: Some('n'), kind: Flag },
    OptSpec { long: "squeeze-blank", short: Some('s'), kind: Flag },
    OptSpec { long: "", short: Some('t'), kind: Flag },
    OptSpec { long: "show-tabs", short: Some('T'), kind: Flag },
    OptSpec { long: "show-nonprinting", short: Some('v'), kind: Flag },
    OptSpec { long: "", short: Some('u'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("cat", OPTS, uu_cat::uumain, &case);
});
