// Generated by fuzzing/gen_targets.py from `cut --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "bytes", short: Some('b'), kind: Value },
    OptSpec { long: "characters", short: Some('c'), kind: Value },
    OptSpec { long: "delimiter", short: Some('d'), kind: Value },
    OptSpec { long: "", short: Some('w'), kind: Flag },
    OptSpec { long: "fields", short: Some('f'), kind: Value },
    OptSpec { long: "complement", short: None, kind: Flag },
    OptSpec { long: "only-delimited", short: Some('s'), kind: Flag },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
    OptSpec { long: "output-delimiter", short: None, kind: Value },
    OptSpec { long: "", short: Some('n'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("cut", OPTS, uu_cut::uumain, &case);
});
