// Generated by fuzzing/gen_targets.py from `paste --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "serial", short: Some('s'), kind: Flag },
    OptSpec { long: "delimiters", short: Some('d'), kind: Value },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("paste", OPTS, uu_paste::uumain, &case);
});
