// Generated by fuzzing/gen_targets.py from `chgrp --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "changes", short: Some('c'), kind: Flag },
    OptSpec { long: "silent", short: Some('f'), kind: Flag },
    OptSpec { long: "quiet", short: None, kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "preserve-root", short: None, kind: Flag },
    OptSpec { long: "no-preserve-root", short: None, kind: Flag },
    OptSpec { long: "reference", short: None, kind: Value },
    OptSpec { long: "from", short: None, kind: Value },
    OptSpec { long: "recursive", short: Some('R'), kind: Flag },
    OptSpec { long: "", short: Some('H'), kind: Flag },
    OptSpec { long: "", short: Some('L'), kind: Flag },
    OptSpec { long: "", short: Some('P'), kind: Flag },
    OptSpec { long: "dereference", short: None, kind: Flag },
    OptSpec { long: "no-dereference", short: Some('h'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("chgrp", OPTS, uu_chgrp::uumain, &case);
});
