// Generated by fuzzing/gen_targets.py from `split --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "bytes", short: Some('b'), kind: Value },
    OptSpec { long: "line-bytes", short: Some('C'), kind: Value },
    OptSpec { long: "lines", short: Some('l'), kind: Value },
    OptSpec { long: "number", short: Some('n'), kind: Value },
    OptSpec { long: "additional-suffix", short: None, kind: Value },
    OptSpec { long: "filter", short: None, kind: Value },
    OptSpec { long: "elide-empty-files", short: Some('e'), kind: Flag },
    OptSpec { long: "", short: Some('d'), kind: Flag },
    OptSpec { long: "", short: Some('x'), kind: Flag },
    OptSpec { long: "suffix-length", short: Some('a'), kind: Value },
    OptSpec { long: "verbose", short: None, kind: Flag },
    OptSpec { long: "separator", short: Some('t'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("split", OPTS, uu_split::uumain, &case);
});
