// Generated by fuzzing/gen_targets.py from `rmdir --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "ignore-fail-on-non-empty", short: None, kind: Flag },
    OptSpec { long: "parents", short: Some('p'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("rmdir", OPTS, uu_rmdir::uumain, &case);
});
