// Generated by fuzzing/gen_targets.py from `pr --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "pages", short: None, kind: Value },
    OptSpec { long: "header", short: Some('h'), kind: Value },
    OptSpec { long: "date-format", short: Some('D'), kind: Value },
    OptSpec { long: "double-space", short: Some('d'), kind: Flag },
    OptSpec { long: "number-lines", short: Some('n'), kind: Value },
    OptSpec { long: "first-line-number", short: Some('N'), kind: Value },
    OptSpec { long: "omit-header", short: Some('t'), kind: Flag },
    OptSpec { long: "omit-pagination", short: Some('T'), kind: Flag },
    OptSpec { long: "length", short: Some('l'), kind: Value },
    OptSpec { long: "no-file-warnings", short: Some('r'), kind: Flag },
    OptSpec { long: "form-feed", short: Some('F'), kind: Flag },
    OptSpec { long: "width", short: Some('w'), kind: Value },
    OptSpec { long: "page-width", short: Some('W'), kind: Value },
    OptSpec { long: "across", short: Some('a'), kind: Flag },
    OptSpec { long: "column", short: None, kind: Value },
    OptSpec { long: "separator", short: Some('s'), kind: Optional },
    OptSpec { long: "sep-string", short: Some('S'), kind: Optional },
    OptSpec { long: "merge", short: Some('m'), kind: Flag },
    OptSpec { long: "indent", short: Some('o'), kind: Value },
    OptSpec { long: "", short: Some('J'), kind: Flag },
    OptSpec { long: "expand-tabs", short: Some('e'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("pr", OPTS, uu_pr::uumain, &case);
});
