// Generated by fuzzing/gen_targets.py from `od --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "address-radix", short: Some('A'), kind: Value },
    OptSpec { long: "skip-bytes", short: Some('j'), kind: Value },
    OptSpec { long: "read-bytes", short: Some('N'), kind: Value },
    OptSpec { long: "endian", short: None, kind: Value },
    OptSpec { long: "strings", short: Some('S'), kind: Optional },
    OptSpec { long: "", short: Some('a'), kind: Flag },
    OptSpec { long: "", short: Some('b'), kind: Flag },
    OptSpec { long: "", short: Some('c'), kind: Flag },
    OptSpec { long: "", short: Some('d'), kind: Flag },
    OptSpec { long: "", short: Some('D'), kind: Flag },
    OptSpec { long: "", short: Some('o'), kind: Flag },
    OptSpec { long: "", short: Some('I'), kind: Flag },
    OptSpec { long: "", short: Some('L'), kind: Flag },
    OptSpec { long: "", short: Some('i'), kind: Flag },
    OptSpec { long: "", short: Some('l'), kind: Flag },
    OptSpec { long: "", short: Some('x'), kind: Flag },
    OptSpec { long: "", short: Some('h'), kind: Flag },
    OptSpec { long: "", short: Some('O'), kind: Flag },
    OptSpec { long: "", short: Some('s'), kind: Flag },
    OptSpec { long: "", short: Some('X'), kind: Flag },
    OptSpec { long: "", short: Some('H'), kind: Flag },
    OptSpec { long: "", short: Some('e'), kind: Flag },
    OptSpec { long: "", short: Some('f'), kind: Flag },
    OptSpec { long: "", short: Some('F'), kind: Flag },
    OptSpec { long: "format", short: Some('t'), kind: Value },
    OptSpec { long: "output-duplicates", short: Some('v'), kind: Flag },
    OptSpec { long: "width", short: Some('w'), kind: Optional },
    OptSpec { long: "traditional", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("od", OPTS, uu_od::uumain, &case);
});
