// Generated by fuzzing/gen_targets.py from `nl --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "body-numbering", short: Some('b'), kind: Value },
    OptSpec { long: "section-delimiter", short: Some('d'), kind: Value },
    OptSpec { long: "footer-numbering", short: Some('f'), kind: Value },
    OptSpec { long: "header-numbering", short: Some('h'), kind: Value },
    OptSpec { long: "line-increment", short: Some('i'), kind: Value },
    OptSpec { long: "join-blank-lines", short: Some('l'), kind: Value },
    OptSpec { long: "number-format", short: Some('n'), kind: Value },
    OptSpec { long: "no-renumber", short: Some('p'), kind: Flag },
    OptSpec { long: "number-separator", short: Some('s'), kind: Value },
    OptSpec { long: "starting-line-number", short: Some('v'), kind: Value },
    OptSpec { long: "number-width", short: Some('w'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("nl", OPTS, uu_nl::uumain, &case);
});
