// Generated by fuzzing/gen_targets.py from `numfmt --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "debug", short: None, kind: Flag },
    OptSpec { long: "grouping", short: None, kind: Flag },
    OptSpec { long: "delimiter", short: Some('d'), kind: Value },
    OptSpec { long: "field", short: None, kind: Value },
    OptSpec { long: "format", short: None, kind: Value },
    OptSpec { long: "from", short: None, kind: Value },
    OptSpec { long: "from-unit", short: None, kind: Value },
    OptSpec { long: "to", short: None, kind: Value },
    OptSpec { long: "to-unit", short: None, kind: Value },
    OptSpec { long: "padding", short: None, kind: Value },
    OptSpec { long: "header", short: None, kind: Optional },
    OptSpec { long: "round", short: None, kind: Value },
    OptSpec { long: "suffix", short: None, kind: Value },
    OptSpec { long: "unit-separator", short: None, kind: Value },
    OptSpec { long: "invalid", short: None, kind: Value },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("numfmt", OPTS, uu_numfmt::uumain, &case);
});
