// Generated by fuzzing/gen_targets.py from `csplit --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "suffix-format", short: Some('b'), kind: Value },
    OptSpec { long: "prefix", short: Some('f'), kind: Value },
    OptSpec { long: "keep-files", short: Some('k'), kind: Flag },
    OptSpec { long: "suppress-matched", short: None, kind: Flag },
    OptSpec { long: "digits", short: Some('n'), kind: Value },
    OptSpec { long: "quiet", short: Some('q'), kind: Flag },
    OptSpec { long: "elide-empty-files", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("csplit", OPTS, uu_csplit::uumain, &case);
});
