// Generated by fuzzing/gen_targets.py from `touch --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('a'), kind: Flag },
    OptSpec { long: "", short: Some('t'), kind: Value },
    OptSpec { long: "date", short: Some('d'), kind: Value },
    OptSpec { long: "", short: Some('f'), kind: Flag },
    OptSpec { long: "", short: Some('m'), kind: Flag },
    OptSpec { long: "no-create", short: Some('c'), kind: Flag },
    OptSpec { long: "no-dereference", short: Some('h'), kind: Flag },
    OptSpec { long: "reference", short: Some('r'), kind: Value },
    OptSpec { long: "time", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("touch", OPTS, uu_touch::uumain, &case);
});
