// Generated by fuzzing/gen_targets.py from `ln --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "", short: Some('b'), kind: Flag },
    OptSpec { long: "force", short: Some('f'), kind: Flag },
    OptSpec { long: "interactive", short: Some('i'), kind: Flag },
    OptSpec { long: "no-dereference", short: Some('n'), kind: Flag },
    OptSpec { long: "logical", short: Some('L'), kind: Flag },
    OptSpec { long: "physical", short: Some('P'), kind: Flag },
    OptSpec { long: "symbolic", short: Some('s'), kind: Flag },
    OptSpec { long: "suffix", short: Some('S'), kind: Value },
    OptSpec { long: "target-directory", short: Some('t'), kind: Value },
    OptSpec { long: "no-target-directory", short: Some('T'), kind: Flag },
    OptSpec { long: "relative", short: Some('r'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("ln", OPTS, uu_ln::uumain, &case);
});
