// Generated by fuzzing/gen_targets.py from `wc --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "bytes", short: Some('c'), kind: Flag },
    OptSpec { long: "chars", short: Some('m'), kind: Flag },
    OptSpec { long: "files0-from", short: None, kind: Value },
    OptSpec { long: "lines", short: Some('l'), kind: Flag },
    OptSpec { long: "max-line-length", short: Some('L'), kind: Flag },
    OptSpec { long: "total", short: None, kind: Value },
    OptSpec { long: "words", short: Some('w'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("wc", OPTS, uu_wc::uumain, &case);
});
