// Generated by fuzzing/gen_targets.py from `chroot --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "groups", short: None, kind: Value },
    OptSpec { long: "userspec", short: None, kind: Value },
    OptSpec { long: "skip-chdir", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("chroot", OPTS, uu_chroot::uumain, &case);
});
