// Generated by fuzzing/gen_targets.py from `stat --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "dereference", short: Some('L'), kind: Flag },
    OptSpec { long: "file-system", short: Some('f'), kind: Flag },
    OptSpec { long: "terse", short: Some('t'), kind: Flag },
    OptSpec { long: "format", short: Some('c'), kind: Value },
    OptSpec { long: "printf", short: None, kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("stat", OPTS, uu_stat::uumain, &case);
});
