// Generated by fuzzing/gen_targets.py from `sort --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "sort", short: None, kind: Value },
    OptSpec { long: "human-numeric-sort", short: Some('h'), kind: Flag },
    OptSpec { long: "month-sort", short: Some('M'), kind: Flag },
    OptSpec { long: "numeric-sort", short: Some('n'), kind: Flag },
    OptSpec { long: "general-numeric-sort", short: Some('g'), kind: Flag },
    OptSpec { long: "random-sort", short: Some('R'), kind: Flag },
    OptSpec { long: "random-source", short: None, kind: Value },
    OptSpec { long: "dictionary-order", short: Some('d'), kind: Flag },
    OptSpec { long: "merge", short: Some('m'), kind: Flag },
    OptSpec { long: "check-silent", short: Some('C'), kind: Flag },
    OptSpec { long: "ignore-case", short: Some('f'), kind: Flag },
    OptSpec { long: "ignore-nonprinting", short: Some('i'), kind: Flag },
    OptSpec { long: "ignore-leading-blanks", short: Some('b'), kind: Flag },
    OptSpec { long: "output", short: Some('o'), kind: Value },
    OptSpec { long: "reverse", short: Some('r'), kind: Flag },
    OptSpec { long: "stable", short: Some('s'), kind: Flag },
    OptSpec { long: "unique", short: Some('u'), kind: Flag },
    OptSpec { long: "key", short: Some('k'), kind: Value },
    OptSpec { long: "field-separator", short: Some('t'), kind: Value },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
    OptSpec { long: "parallel", short: None, kind: Value },
    OptSpec { long: "buffer-size", short: Some('S'), kind: Value },
    OptSpec { long: "temporary-directory", short: Some('T'), kind: Value },
    OptSpec { long: "compress-program", short: None, kind: Value },
    OptSpec { long: "batch-size", short: None, kind: Value },
    OptSpec { long: "files0-from", short: None, kind: Value },
    OptSpec { long: "debug", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("sort", OPTS, uu_sort::uumain, &case);
});
