// Generated by fuzzing/gen_targets.py from `df --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "all", short: Some('a'), kind: Flag },
    OptSpec { long: "block-size", short: Some('B'), kind: Value },
    OptSpec { long: "total", short: None, kind: Flag },
    OptSpec { long: "human-readable", short: Some('h'), kind: Flag },
    OptSpec { long: "si", short: Some('H'), kind: Flag },
    OptSpec { long: "inodes", short: Some('i'), kind: Flag },
    OptSpec { long: "", short: Some('k'), kind: Flag },
    OptSpec { long: "local", short: Some('l'), kind: Flag },
    OptSpec { long: "no-sync", short: None, kind: Flag },
    OptSpec { long: "portability", short: Some('P'), kind: Flag },
    OptSpec { long: "sync", short: None, kind: Flag },
    OptSpec { long: "type", short: Some('t'), kind: Value },
    OptSpec { long: "print-type", short: Some('T'), kind: Flag },
    OptSpec { long: "exclude-type", short: Some('x'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("df", OPTS, uu_df::uumain, &case);
});
