// Generated by fuzzing/gen_targets.py from `cksum --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "algorithm", short: Some('a'), kind: Value },
    OptSpec { long: "untagged", short: None, kind: Flag },
    OptSpec { long: "tag", short: None, kind: Flag },
    OptSpec { long: "length", short: Some('l'), kind: Value },
    OptSpec { long: "raw", short: None, kind: Flag },
    OptSpec { long: "check", short: Some('c'), kind: Flag },
    OptSpec { long: "warn", short: Some('w'), kind: Flag },
    OptSpec { long: "status", short: None, kind: Flag },
    OptSpec { long: "quiet", short: None, kind: Flag },
    OptSpec { long: "ignore-missing", short: None, kind: Flag },
    OptSpec { long: "strict", short: None, kind: Flag },
    OptSpec { long: "base64", short: None, kind: Flag },
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
    OptSpec { long: "debug", short: None, kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("cksum", OPTS, uu_cksum::uumain, &case);
});
