// Generated by fuzzing/gen_targets.py from `seq --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "separator", short: Some('s'), kind: Value },
    OptSpec { long: "terminator", short: Some('t'), kind: Value },
    OptSpec { long: "equal-width", short: Some('w'), kind: Flag },
    OptSpec { long: "format", short: Some('f'), kind: Value },
];

fuzz_target!(|case: Case| {
    let _ = run("seq", OPTS, uu_seq::uumain, &case);
});
