// Generated by fuzzing/gen_targets.py from `head --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "bytes", short: Some('c'), kind: Value },
    OptSpec { long: "lines", short: Some('n'), kind: Value },
    OptSpec { long: "quiet", short: Some('q'), kind: Flag },
    OptSpec { long: "verbose", short: Some('v'), kind: Flag },
    OptSpec { long: "zero-terminated", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("head", OPTS, uu_head::uumain, &case);
});
