// Generated by fuzzing/gen_targets.py from `dirname --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
    OptSpec { long: "zero", short: Some('z'), kind: Flag },
];

fuzz_target!(|case: Case| {
    let _ = run("dirname", OPTS, uu_dirname::uumain, &case);
});
