// Generated by fuzzing/gen_targets.py from `chcon --help`; do not edit.
#![no_main]
#![allow(unused_imports)]
use libfuzzer_sys::fuzz_target;
use uufuzz::generic::{ArgKind::*, Case, OptSpec, run};

static OPTS: &[OptSpec] = &[
];

fuzz_target!(|case: Case| {
    let _ = run("chcon", OPTS, uu_chcon::uumain, &case);
});
